### ISSUE TITLE
Upgrade constraint to React 17+ and make a new release

### ISSUE THREAD

**Issue by igorsantos07** [neosiae/react-aria-offcanvas#31]
Hello!
We've been using React 17 since December, and had no issues with the package since the upgrade. However, `npm` keeps complaining of the unmet peer dependency, since the package specifically requires React 16.

Is it possible to create a new release with either an update version constraint or a more relaxed one, so this kind of issue doesn't happen again?

Thanks for the work!

**Comment by cedricdelpoux** [comment]
I made a PR #37 to support React 17

**Comment by cedricdelpoux** [comment]
Thanks for merging. Do you plan to release a new version?

**Comment by neosiae** [comment]
I will release it in a few days.

**Comment by cedricdelpoux** [comment]
A little up, just in case you forgot to release

**Comment by neosiae** [comment]
The new version is released.

**Comment by cedricdelpoux** [comment]
Thanks
