### ISSUE TITLE
support React 17

### ISSUE THREAD

**Issue by cedricdelpoux** [neosiae/react-aria-offcanvas#36]
When using **React 17**, there is this annoying warning message

```
react-aria-offcanvas@1.4.2" has incorrect peer dependency "react@^16.4.2".
```

The package works as expected and is already compatible

**Comment by cedricdelpoux** [comment]
I made a PR

**Comment by igorsantos07** [comment]
dup of #31

**Comment by cedricdelpoux** [comment]
Yes sorry. I made a PR #37
