### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by jokokoloko** [neosiae/react-aria-offcanvas#7]
There is another error that I am seeing @neosiae and it is likely that it has been present since v1.2.2 and I am just now noticing it. You can actually see the error yourself here:

https://5cfb8ec560af2f0009be41cf--sleepy-pasteur-0771b3.netlify.com/

Once on this site, click the orange "Free Demo" button on the top right, which will direct you to `/request-demo` which is a page with a form, then click "News", the logo, or any other link that actually has an internal page.

When clicking a link to exit the `/request-demo` page, the majority of the site's markup is deleted, this includes `<div id="offcanvas-root" data-testid="offcanvas-portal">` and anything inside `<div id="___gatsby">`, which is the whole page/site. This is when the `Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.` error appears in the console. This is all very easy to see happen in real time within Google Chrome's DevTools.

The `/request-demo` page contains a form with HTML markup that is being placed from an external source on build. The HTML markup of the form on this page includes some `<script>` tags which could be the cause of this issue due to these tags being nested deep within the site's markup rather than being immediate children of `<body>`.

My guess is that this issue is related to this commit: https://github.com/neosiae/react-aria-offcanvas/commit/084acb0fce1ea33dceb7b8369014cb7f459c3db7

Along with fixing this issue for `<script>` tags that are deeply nested within a given site's markup, you might want to test iframes that contain `<script>` tags as well.

I have verified that this issue and error do not appear in v1.2.1, which is the version I have reverted back to.

Here are some screenshots to go along with this issue.

Before error:
![Screen Shot 2019-06-09 at 7 31 10 PM](https://user-images.githubusercontent.com/5240653/59171212-d1ebf300-8af6-11e9-9d5b-bd8607cac219.png)

After error:
![Screen Shot 2019-06-09 at 7 31 54 PM](https://user-images.githubusercontent.com/5240653/59171226-e29c6900-8af6-11e9-88e0-4e7dea703040.png)

Error message (ignore yellow warnings as those are from Gatsby itself):
![Screen Shot 2019-06-09 at 7 32 27 PM](https://user-images.githubusercontent.com/5240653/59171249-f5af3900-8af6-11e9-8c99-d8dcc2cc7941.png)

**Comment by neosiae** [comment]
@jokokoloko Thanks again! I removed `Node.insertBefore()`, there is no need at all to do that. Please update to the latest version. Should be fixed.

**Comment by jokokoloko** [comment]
I upgraded to version 1.3.2 and everything is working great! No errors! Thanks again!
